"""
PASS — Run Entry Point
========================
Application entry point with CLI commands for database
initialization and seeding demo data.

Usage:
    python run.py                  # Start development server
    python run.py --seed           # Seed database with demo data
    python run.py --reset          # Drop & recreate tables, then seed
"""

import sys
import os
import uuid
import random
from datetime import datetime, timedelta, timezone

# Ensure the project root is in the path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from app import create_app, db
from models import User, Course, Student, Submission, Alert, PolicyEvent

app = create_app()


def init_db():
    """Create all database tables."""
    with app.app_context():
        db.create_all()
        print("[✓] Database tables created.")


def seed_demo_data():
    """
    Seed the database with realistic demo data.
    Creates:
      - 2 user accounts (instructor + student)
      - 3 courses
      - 30 students across courses
      - ~300 submissions with varied Δt patterns
      - Alerts and policy events generated by engine recomputation
    """
    from engine.metrics import MetricComputer
    from engine.hysteresis import HysteresisFilter
    from engine.credibility import CredibilityScorer

    mc = MetricComputer()
    hf = HysteresisFilter()
    cs = CredibilityScorer()

    with app.app_context():
        # Skip if data already exists
        if User.query.first():
            print("[i] Database already has data. Use --reset to recreate.")
            return

        print("[...] Seeding demo data...")

        # ── Users ───────────────────────────────────────────────
        instructor_user = User(
            username="instructor",
            email="instructor@pass.edu",
            full_name="Dr. Meera Sharma",
            role="instructor",
        )
        instructor_user.set_password("password123")

        student_user = User(
            username="arjun",
            email="arjun@pass.edu",
            full_name="Arjun Mehta",
            role="student",
        )
        student_user.set_password("password123")

        admin_user = User(
            username="admin",
            email="admin@pass.edu",
            full_name="System Admin",
            role="admin",
        )
        admin_user.set_password("admin123")

        db.session.add_all([instructor_user, student_user, admin_user])
        db.session.flush()

        # ── Courses ─────────────────────────────────────────────
        courses_data = [
            ("CS501", "Data Structures & Algorithms", "2024-25 Odd"),
            ("CS502", "Database Management Systems", "2024-25 Odd"),
            ("CS503", "Software Engineering", "2024-25 Odd"),
        ]
        courses = []
        for cid, name, sem in courses_data:
            c = Course(
                course_id=cid,
                course_name=name,
                semester=sem,
                instructor_id=instructor_user.id,
            )
            db.session.add(c)
            courses.append(c)
        db.session.flush()

        # ── Students ────────────────────────────────────────────
        student_names = [
            "Arjun Mehta", "Priya Reddy", "Karthik Nair", "Sneha Patel",
            "Rohan Gupta", "Aisha Khan", "Vikram Singh", "Divya Krishnan",
            "Sanjay Rao", "Meghna Iyer", "Amit Sharma", "Lakshmi Devi",
            "Rahul Verma", "Kavitha Menon", "Nikhil Joshi", "Pooja Agarwal",
            "Suresh Kumar", "Ananya Bose", "Harsh Vardhan", "Rithika Sundaram",
            "Deepak Pillai", "Swathi Raghavan", "Manoj Tiwari", "Nandini Desai",
            "Siddharth Malhotra", "Bhavana Srinivasan", "Rajesh Pawar",
            "Trisha Mukherjee", "Gaurav Choudhary", "Ishita Banerjee",
        ]

        # Define submission behavior profiles (used for both student creation & submissions)
        profiles = {
            "excellent": {"mean_hours": 24, "std": 6, "miss_rate": 0.0,
                          "attendance": (92, 100), "mid_range": (75, 95)},
            "good": {"mean_hours": 8, "std": 10, "miss_rate": 0.05,
                      "attendance": (82, 95), "mid_range": (60, 85)},
            "average": {"mean_hours": 2, "std": 15, "miss_rate": 0.10,
                         "attendance": (75, 88), "mid_range": (45, 70)},
            "struggling": {"mean_hours": -5, "std": 18, "miss_rate": 0.15,
                            "attendance": (60, 78), "mid_range": (30, 55)},
            "at_risk": {"mean_hours": -12, "std": 22, "miss_rate": 0.25,
                         "attendance": (40, 65), "mid_range": (15, 40)},
            "declining": {"mean_hours": 20, "std": 8, "miss_rate": 0.02,
                           "attendance": (70, 90), "mid_range": (50, 80)},
        }

        profile_assignments = (
            ["excellent"] * 5
            + ["good"] * 8
            + ["average"] * 7
            + ["struggling"] * 5
            + ["at_risk"] * 3
            + ["declining"] * 2
        )

        students = []
        for i, name in enumerate(student_names):
            usn = f"1RV22CS{str(i + 1).zfill(3)}"
            course = courses[i % len(courses)]
            profile_name = profile_assignments[i]
            profile = profiles[profile_name]

            # Generate attendance & mid-term exam scores based on profile
            att_lo, att_hi = profile["attendance"]
            mid_lo, mid_hi = profile["mid_range"]

            attendance_pct = round(random.uniform(att_lo, att_hi), 1)
            mid1 = round(random.uniform(mid_lo, mid_hi), 1)
            mid2 = round(random.uniform(mid_lo, mid_hi), 1)
            mid3 = round(random.uniform(mid_lo, mid_hi), 1)

            s = Student(
                student_id=usn,
                name=name,
                course_id=course.id,
                status="active",
                credibility_score=50.0,  # Will be recomputed
                attendance_pct=attendance_pct,
                mid1_score=mid1,
                mid2_score=mid2,
                mid3_score=mid3,
            )
            # Link the first student to the student_user account
            if name == "Arjun Mehta":
                s.user_id = student_user.id

            db.session.add(s)
            students.append(s)
        db.session.flush()

        # ── Submissions ─────────────────────────────────────────
        # Generate 10 assignments with deadlines over 10 weeks
        base_date = datetime(2025, 1, 13, 23, 59, 0, tzinfo=timezone.utc)
        assignments = [f"A{str(i+1).zfill(2)}" for i in range(10)]
        deadlines = [base_date + timedelta(weeks=i) for i in range(10)]

        all_submissions = []
        for idx, student in enumerate(students):
            profile_name = profile_assignments[idx]
            profile = profiles[profile_name]

            for a_idx, (aid, deadline) in enumerate(zip(assignments, deadlines)):
                # Skip some assignments based on miss_rate
                if random.random() < profile["miss_rate"]:
                    continue

                # Calculate Δt hours with some progression
                base_dt_hours = profile["mean_hours"]

                # For declining profile, reduce Δt over time
                if profile_name == "declining":
                    base_dt_hours = max(profile["mean_hours"] - a_idx * 5, -20)

                dt_hours = random.gauss(base_dt_hours, profile["std"])
                dt_hours = max(min(dt_hours, 72), -48)  # Clamp

                delta_t_seconds = dt_hours * 3600
                submitted_at = deadline - timedelta(hours=dt_hours)

                status = "on_time" if dt_hours >= 0 else "late"

                sub = Submission(
                    submission_id=f"SUB-{uuid.uuid4().hex[:8].upper()}",
                    student_id=student.id,
                    assignment_id=aid,
                    course_id_ref=student.course_id,
                    submitted_at=submitted_at,
                    deadline=deadline,
                    delta_t=delta_t_seconds,
                    delta_t_hours=round(dt_hours, 2),
                    submission_status=status,
                )
                db.session.add(sub)
                all_submissions.append(sub)

        db.session.flush()
        print(f"  [+] {len(students)} students, {len(all_submissions)} submissions created.")

        # ── Recompute All Metrics ───────────────────────────────
        print("  [...] Computing credibility scores & alerts...")

        alert_count = 0
        policy_count = 0

        for student in students:
            subs = Submission.query.filter_by(
                student_id=student.id
            ).order_by(Submission.submitted_at.asc()).all()

            if not subs:
                continue

            delta_t_values = [s.delta_t for s in subs]
            summary = mc.compute_student_summary(delta_t_values)
            variance_series = mc.compute_rolling_variance_series(delta_t_values)

            total_assignments = 10  # We created 10 assignments
            prev_score = student.credibility_score

            cred_result = cs.compute_credibility_score(
                delta_t_values=delta_t_values,
                variance_value=summary["current_variance"],
                submitted_count=len(subs),
                total_assignments=total_assignments,
                attendance_pct=student.attendance_pct or 0.0,
                mid1=student.mid1_score,
                mid2=student.mid2_score,
                mid3=student.mid3_score,
                historical_variances=[v for v in variance_series if v is not None],
            )
            student.credibility_score = cred_result["overall_score"]

            # Hysteresis analysis
            valid_variances = [v for v in variance_series if v is not None]
            analysis = hf.run_full_analysis(
                delta_t_values=delta_t_values,
                variance_values=valid_variances,
                existing_alerts=[],
            )

            for alert_data in analysis["new_alerts"]:
                alert = Alert(
                    alert_id=alert_data["alert_id"],
                    student_id=student.id,
                    metric=alert_data["metric"],
                    pct_change=alert_data["pct_change"],
                    window_size=alert_data["window_size"],
                    severity=alert_data["severity"],
                    description=alert_data["description"],
                )
                db.session.add(alert)
                alert_count += 1

            # Policy triggers
            policy_events = cs.check_policy_triggers(
                cred_result["overall_score"], prev_score
            )
            for event_data in policy_events:
                event = PolicyEvent(
                    event_id=f"POL-{uuid.uuid4().hex[:8].upper()}",
                    student_id=student.id,
                    policy_type=event_data["policy_type"],
                    description=event_data["description"],
                    triggered_at=event_data["triggered_at"],
                    expires_at=event_data.get("expires_at"),
                )
                db.session.add(event)
                policy_count += 1

        db.session.commit()
        print(f"  [+] {alert_count} alerts, {policy_count} policy events generated.")
        print("[✓] Demo data seeded successfully!")
        print()
        print("  Demo Accounts:")
        print("  ─────────────────────────────────")
        print("  Instructor:  instructor / password123")
        print("  Student:     arjun / password123")
        print("  Admin:       admin / admin123")


def reset_db():
    """Drop all tables and recreate."""
    with app.app_context():
        db.drop_all()
        print("[✓] All tables dropped.")
        db.create_all()
        print("[✓] Tables recreated.")


if __name__ == "__main__":
    if "--reset" in sys.argv:
        reset_db()
        seed_demo_data()
    elif "--seed" in sys.argv:
        init_db()
        seed_demo_data()
    else:
        init_db()
        print()
        print("  ╔══════════════════════════════════════════╗")
        print("  ║   PASS — Proactive Academic Support      ║")
        print("  ║   http://127.0.0.1:5000                  ║")
        print("  ╚══════════════════════════════════════════╝")
        print()
        app.run(debug=True, host="127.0.0.1", port=5000)
